version: '3.8'
services:
  currency-exchange:
    image: devbith/spring-microservice-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.SLEUTH.SAMPLER.BASEURL: http://host.docker.internal:9411/

  currency-conversion:
    image: devbith/spring-microservice-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.SLEUTH.SAMPLER.BASEURL: http://host.docker.internal:9411/

  api-gateway:
    image: devbith/spring-microservice-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.SLEUTH.SAMPLER.BASEURL: http://host.docker.internal:9411/

  naming-server:
    image: devbith/spring-microservice-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - currency-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    depends_on:
      - rabbitmq
    restart: always
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
    networks:
      - currency-network

networks:
  currency-network: