spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      baseUrl: http://localhost:9411
      probability: 1.0
server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

