spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com-devbith:devbith/spring-cloud-example-project01-configs.git
server:
  port: 8888
